[package]
name = "sol-counter-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.3.0"
borsh = "1.3.1"
borsh-derive = "1.3.1"

[dev-dependencies]
solana-program-test = "2.3.0"
solana-sdk = "2.3.0"
